language: cpp

compiler:
  - gcc

env:
  global:
    - ROOT_VERSION=6.06.00
  matrix:
    - PROJECT="Factories"
    - PROJECT="common"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - git
      - make
      - cmake
      - uuid-dev
      - libboost1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-system1.55-dev

install:
  - wget http://sbrochet.web.cern.ch/sbrochet/public/ROOT-${ROOT_VERSION}_Python-2.7_Ubuntu-12.04_gcc4.9.tar.xz
  - mkdir root
  - cd root
  - tar xf ../ROOT-${ROOT_VERSION}_Python-2.7_Ubuntu-12.04_gcc4.9.tar.xz
  - source bin/thisroot.sh
  - cd ..

before_script:
  - export CXX=g++-4.9
  - export CC=gcc-4.9
  - export BUILD_DIR="${PROJECT}/build"
  - if [[ $PROJECT != "common" ]]; then mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR} && cmake ..; else cd common/tests; fi

script:
  - make
  - if [[ $PROJECT == "common" ]]; then ./tests.exe; fi

os:
  - linux
